Repository kubernetes/frakti, pull requests merged in 2018-02, with the labels that each got.

#283 Fix variable name typo
  pkg/hyper/images_test.go
Labels: cncf-cla: yes, lgtm, size/S

#285 fix typos in comments
  pkg/hyper/extractor.go
  pkg/hyper/hyper_checkpoint_test.go
  pkg/hyper/ocicni/ocicni.go
  pkg/hyper/sandbox_test.go
  pkg/hyper/streaming_test.go
  pkg/unikernel/image/storage.go
  pkg/unikernel/libvirt/domain.go
  pkg/unikernel/libvirt/vmtools.go
  pkg/unikernel/metadata/container.go
  pkg/unikernel/metadata/sandbox.go
  pkg/unikernel/service/sandbox.go
  pkg/util/downloader/downloader.go
Labels: cncf-cla: yes, lgtm, size/M

#292 fix a typo in alternativeruntime
  pkg/util/alternativeruntime/alternativeruntime.go
Labels: cncf-cla: yes, lgtm, size/XS

#290 Share flexvolume option file json format
  pkg/flexvolume/cinder/flexvolume.go
  pkg/flexvolume/gcepd/flexvolume.go
  pkg/flexvolume/metadata.go
  pkg/flexvolume/metadata_test.go
  pkg/hyper/container.go
  pkg/util/knownflags/consts.go
  pkg/util/metadata/metadata.go
Labels: cncf-cla: yes, lgtm, size/L

#302 hyper: supply interface MTU
  pkg/hyper/network.go
  pkg/hyper/sandbox.go
Labels: cncf-cla: yes, lgtm, size/XS

#284 Fix typo: faild -> failed
  pkg/hyper/network.go
Labels: cncf-cla: yes, lgtm, size/XS

#300 Fix function name typo
  pkg/hyper/helper.go
  pkg/hyper/sandbox.go
Labels: cncf-cla: yes, lgtm, size/XS

#301 Refactor image name standardize actions to a function
  pkg/unikernel/image/image.go
Labels: cncf-cla: yes, lgtm, size/M

#299 Fix various var name typo
  pkg/hyper/fake_client_interface_test.go
  pkg/hyper/helper.go
Labels: cncf-cla: yes, lgtm, size/S

#293 Fix: fix pkg/manager golint warnings
  pkg/manager/manager.go
Labels: cncf-cla: yes, lgtm, size/S
