Repository kubernetes/frakti, pull requests merged in 2018-07, with the labels that each got.

#335 Implement five tasks
  pkg/kata/proc/init.go
  pkg/kata/proc/init_state.go
  pkg/kata/process.go
  pkg/kata/task.go
Labels: cncf-cla: yes, lgtm, size/L

#337 Fix: deploy document
  docs/deploy.md
Labels: cncf-cla: yes, lgtm, size/XS

#339 Implement runtime's fundamental functions
  pkg/kata/proc/exec.go
  pkg/kata/proc/exec_state.go
  pkg/kata/proc/init.go
  pkg/kata/proc/init_state.go
  pkg/kata/proc/process.go
  pkg/kata/proc/types.go
  pkg/kata/process.go
  pkg/kata/runtime.go
  pkg/kata/server/container.go
  pkg/kata/server/sandbox.go
  pkg/kata/task.go
  vendor/github.com/kata-containers/agent/protocols/client/client.go
Labels: cncf-cla: yes, lgtm, size/XL
