Repository kubernetes/frakti, pull requests merged in 2018-03, with the labels that each got.

#308 Typo fix "Fannel"->"Flannel"
  docs/deploy.md
Labels: cncf-cla: yes, lgtm, size/XS

#306 Cleanup flexvolume
  pkg/flexvolume/cinder/flexvolume.go
  pkg/flexvolume/gcepd/flexvolume.go
  pkg/flexvolume/metadata.go
Labels: cncf-cla: yes, lgtm, size/S

#309 Fix: update frakti version
  cluster/allinone.sh
  cmd/frakti/frakti.go
  docs/deploy.md
Labels: cncf-cla: yes, size/XS

#305 add a new flag pod-infra-container-image to override default sandbox image
  cmd/frakti/frakti.go
  pkg/docker/privilegedruntime.go
Labels: cncf-cla: yes, lgtm, size/XS

#317 Update OWNERS file to track latest commit history
  OWNERS
Labels: cncf-cla: yes

#318 Update CHANGELOG.md
  CHANGELOG.md
Labels: cncf-cla: yes, size/M

#313 Install right version of critool
  hack/test-e2e.sh
Labels: cncf-cla: yes, size/XS

#312 Fix various typos
  pkg/hyper/sandbox.go
  pkg/util/downloader/downloader.go
  pkg/util/metadata/metadata.go
Labels: cncf-cla: yes, lgtm, size/S
